# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c385bb2f2b1c4782706e599afd46673cc817e600900c80173d8ff646f7253d3c6bbe10503f558ff6be764a1611f24cdb633e5c0db661c404dd699a2eda46c5a

test:
  secret_key_base: a2938e0d074e5964ce60d1198690ddebbcf9b786b4316249e8c37304ca8e5ba7c61148a5d14144fb59163e683635742d5e16e43ed5915d2d87956043a03181e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
